import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Foundations & Basements',
      items: [{type: 'autogenerated', dirName: 'foundations'}],
    },
    {
      type: 'category',
      label: 'Roofing',
      items: [{type: 'autogenerated', dirName: 'roofing'}],
    },
    {
      type: 'category',
      label: 'Plumbing',
      items: [{type: 'autogenerated', dirName: 'plumbing'}],
    },
    {
      type: 'category',
      label: 'Electrical',
      items: [{type: 'autogenerated', dirName: 'electrical'}],
    },
    {
      type: 'category',
      label: 'HVAC',
      items: [{type: 'autogenerated', dirName: 'hvac'}],
    },
    {
      type: 'category',
      label: 'Exterior & Siding',
      items: [{type: 'autogenerated', dirName: 'exterior'}],
    },
    {
      type: 'category',
      label: 'Interior & Finishes',
      items: [{type: 'autogenerated', dirName: 'interior'}],
    },
    {
      type: 'category',
      label: 'Insulation & Ventilation',
      items: [{type: 'autogenerated', dirName: 'insulation'}],
    },
    {
      type: 'category',
      label: 'Fire & Safety',
      items: [{type: 'autogenerated', dirName: 'fire-safety'}],
    },
    {
      type: 'category',
      label: 'Standards of Practice',
      items: [{type: 'autogenerated', dirName: 'standards'}],
    },
    {
      type: 'category',
      label: 'Business & Marketing',
      items: [{type: 'autogenerated', dirName: 'business'}],
    },
  ],
};

export default sidebars;
